remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
- jekyll-include-cache

locale: "en-US"
title: "My academic webpage"
name: "Daithi Martin"
description: "A personal academic website demonstration"
url: "https://daithimartin.github.io"
search: true
logo: "img.png"
author:
  name : "Daithi Martin"
  avatar : "img.png"
  bio : "I am a Computer Science graduate student at the University of Montana"
  location : "UM"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true